docs: RSPEC-2970
kantabile/sonarkube pull request #12
Opened 2023-01-04 14:28 UTC by GimunLee

2023-01-04 16:47 UTC, kok202 requested changes
첫 시작👍 꾸준히 가시죵
번역은 취향 차이라 사실 무시해주셔도 될 것 같은데요. 
태그 놓치신 게 있는 것 같아서 RC 달고 갑니다.

2023-01-04 16:47 UTC, kok202 commented on _posts/2023-01-04-RSPEC-2970.md
> +tags: [java, test, assertj, mockito]
Blocker랑 CodeSmell 도 추가해주세요~~

2023-01-04 16:47 UTC, kok202 commented on _posts/2023-01-04-RSPEC-2970.md
> +어떤 테스트 프레임워크를 사용할 때, 작성이 완료되지 않은 `assertions`을 사용하는 것은 매우 쉽습니다. 이 룰은 다음 케이스에 `assertions`를 완료하도록 강제합니다.
"어떤 테스트 프레임워크를 사용할 때, 작성이 완료되지 않은 `assertions`을 사용하는 것은 매우 쉽습니다."
보다 
"테스트 프레임워크를 사용할 때, 작성이 덜 끝난 `assertions`을 사용하기 쉽습니다."가 조금 더 뉘앙스적으로 괜찮을것 같습니다.

2023-01-05 08:45 UTC, GimunLee commented on _posts/2023-01-04-RSPEC-2970.md
> +어떤 테스트 프레임워크를 사용할 때, 작성이 완료되지 않은 `assertions`을 사용하는 것은 매우 쉽습니다. 이 룰은 다음 케이스에 `assertions`를 완료하도록 강제합니다.
수정 완료했습니다. 감사합니다.

2023-01-05 10:13 UTC, isangu approved these changes
들여쓰기만 수정해주시면 머지해도 괜찮을 것 같습니다!
수고하셨습니다! 👍

2023-01-05 10:13 UTC, isangu commented on _posts/2023-01-04-RSPEC-2970.md
> +        Mockito.verify(mockedList); // 규칙을 어긴 코드; 여기서 확인된 것은 없습니다. verify()에 연결된 호출이 없습니다.
indent 가 `boolean result = performAction();` 과 동일한 수준이어야 될 것 같습니다.
수정해주시면 감사하겠습니다! 🙇‍♂️🙇‍♂️

2023-01-05 10:13 UTC, isangu commented on _posts/2023-01-04-RSPEC-2970.md
> +// Fest
이거 혹시 Fest 는 어떤의미일까요..??? 원문에도 Fest 인데 의미를 도통 모르겠네요.. 😅

2023-01-05 10:13 UTC, isangu commented on _posts/2023-01-04-RSPEC-2970.md
> +        Mockito.verify(mockedList).clear(); // 규칙을 준수한 해결책
indent 가 `boolean result = performAction();` 과 동일한 수준이어야 될 것 같습니다.
수정해주시면 감사하겠습니다! 🙇‍♂️🙇‍♂️

2023-01-05 12:56 UTC, kok202 approved these changes
리뷰 반영해주셔서 approve 걸어둘게요. @isangu 리뷰만 반영해주시면 될 듯 합니다!

2023-01-07 16:36 UTC, merged

2023-01-09 04:10 UTC, GimunLee commented on _posts/2023-01-04-RSPEC-2970.md
> +// Fest
Fixtures for Easy Software Testing(FEST) 라고 합니다.
FEST is a collection of libraries, released under the Apache 2.0 license, whose mission is to simplify software testing.
출처: https://code.google.com/archive/p/fest/

2023-01-09 04:11 UTC, GimunLee commented
@kok202 앗 머지를 하셨군요. 다른 PR에서 슬며시 수정해놓을게요. (indent)