docs: RSPEC-2129, RSPEC-4276, RSPEC-2694
kantabile/sonarkube pull request #13
Opened 2023-01-04 16:48 UTC by kok202

2023-01-05 08:57 UTC, GimunLee requested changes
수고하셨습니다. 코멘트 확인 부탁드려요~

2023-01-05 08:57 UTC, GimunLee commented on _posts/2023-01-05-RSPEC-2129.md
> +title: '"String", "BigInteger", "BigDecimal" 같은 기본 자료형의 랩핑 클래스 생성자를 사용하지 말아야합니다.'
Nit: 저는 랩핑 말고 래퍼가 더 익숙하기는 한데 중요하진 않을 것 같네요.

2023-01-05 08:57 UTC, GimunLee commented on _posts/2023-01-05-RSPEC-4276.md
> +title: "소유 클래스를 참조하지 않는 내부 클래스는 "static"이어야 합니다"
원문 제목이랑 다른 것 같아요~
원문 제목: "Functional Interfaces should be as specialised as possible"

2023-01-05 10:34 UTC, isangu approved these changes
매일매일 엄청난 작업량입니다.. 😲
리키의견 외에는 저도 코멘트 남길 것은 없어서 Approve 합니다.
제목 수정 및 nit 코멘트만 고민해봐주시면 감사하겠습니다~

2023-01-05 10:34 UTC, isangu commented on _posts/2023-01-05-RSPEC-2129.md
> +title: '"String", "BigInteger", "BigDecimal" 같은 기본 자료형의 랩핑 클래스 생성자를 사용하지 말아야합니다.'
중요하진 않지만 저도 보통 wrapper classes 라고 부르는 것으로 알고 있어서, 래퍼에 한표 드립니다.

2023-01-05 12:53 UTC, kok202 commented on _posts/2023-01-05-RSPEC-4276.md
> +title: "소유 클래스를 참조하지 않는 내부 클래스는 "static"이어야 합니다"
제목 잘못 입력하는 실수가 종종있네요. 감사합니다!

2023-01-09 04:23 UTC, GimunLee approved these changes

2023-01-13 00:57 UTC, merged