RSPEC-6103, RSPEC-5967
kantabile/sonarkube pull request #22
Opened 2023-01-13 07:04 UTC by GimunLee

2023-01-13 15:57 UTC, kok202 requested changes
수고하셨습니다! 👍 리뷰 한번만 확인해주세용

2023-01-13 15:57 UTC, kok202 commented on _posts/2023-01-12-RSPEC-5967.md
> +`Unit` 테스트를 이상의 테스트와 관련된 주석으로 주석 처리하는 것은 쓸모없을 뿐 아니라 테스트 실패 또는 원하지 않는 부작용과 같은 사이드 이펙트가 발생할 수 있습니다.
요거 문장 잘 안읽히는데, 한번만 확인 부탁드립니다.

2023-01-13 15:57 UTC, kok202 commented on _posts/2023-01-12-RSPEC-5967.md
> +`Unit` 테스트를 이상의 테스트와 관련된 주석으로 주석 처리하는 것은 쓸모없을 뿐 아니라 테스트 실패 또는 원하지 않는 부작용과 같은 사이드 이펙트가 발생할 수 있습니다.
마찬가지로 주석보다는 어노테이션이라는 이름으로 번역하는게 더 나을 것 같네요.

2023-01-13 15:57 UTC, kok202 commented on _posts/2023-01-12-RSPEC-6103.md
> +title: '"Consumer" 인수를 사용하는 "AssertJ assertions"는 "consumers"에 "assertion"을 포함해야 합니다.'
'"Consumer" 인수를 사용하는 "AssertJ assertions"는 `Consumer` 인터페이스 안에 "assertion"을 포함해야 합니다.'
요정도가 낫지 않을까요? "consumers"는 변수 이름처럼 보여서 헷갈리니 함수형 인터페이스인 `Consumer` 를 지칭하는 정확한 말로 변경되는게 나아보이네요.

2023-01-14 01:10 UTC, bourbonkk approved these changes
@kok202 가 이야기한 부분만 조금 개선되면 더 좋을것같습니다!
수고많으셨습니다. @GimunLee

2023-01-14 01:10 UTC, bourbonkk commented on _posts/2023-01-12-RSPEC-6103.md
> +title: '"Consumer" 인수를 사용하는 "AssertJ assertions"는 "consumers"에 "assertion"을 포함해야 합니다.'
동의합니다

2023-01-14 01:10 UTC, bourbonkk commented on _posts/2023-01-12-RSPEC-5967.md
> +`Unit` 테스트를 이상의 테스트와 관련된 주석으로 주석 처리하는 것은 쓸모없을 뿐 아니라 테스트 실패 또는 원하지 않는 부작용과 같은 사이드 이펙트가 발생할 수 있습니다.
동의합니다

2023-01-14 11:40 UTC, isangu approved these changes
코멘트 한번 확인해주시고 반영해주시면 감사하겠습니다!
고생하셨습니다 👏👏👏

2023-01-14 11:40 UTC, isangu commented on _posts/2023-01-12-RSPEC-6103.md
> +title: '"Consumer" 인수를 사용하는 "AssertJ assertions"는 "consumers"에 "assertion"을 포함해야 합니다.'
아니면 `Consumer<T>` 정도는 어떠십니까?!

2023-01-14 11:40 UTC, isangu commented on _posts/2023-01-12-RSPEC-6103.md
> +assertThat(myObject).satisfies("Hello"::equals); // 규칙을 어긴 코드 - 문자열 값을 테스트하지 않았다.
주석이 갑자기 해라체(않았다.) 가 됐네요. ㅎㅎ;; `않았습니다` 정도는 어떨까요?

2023-01-17 13:50 UTC, GimunLee commented on _posts/2023-01-12-RSPEC-5967.md
> +`Unit` 테스트를 이상의 테스트와 관련된 주석으로 주석 처리하는 것은 쓸모없을 뿐 아니라 테스트 실패 또는 원하지 않는 부작용과 같은 사이드 이펙트가 발생할 수 있습니다.
이상 앞에 '하나'가 빠졌네요. 피드백 반영했습니다. 👍

2023-01-17 13:53 UTC, isangu commented
바쁘신 와중에 매우 고생하셨습니다 🙇🙇‍♂️🙇🙇‍♂️

2023-01-17 14:07 UTC, merged