java 8번역
kantabile/sonarkube pull request #3
Opened 2022-12-30 03:40 UTC by kok202

- 공유할만한 내용은 readthis 라는 키워드로 태그를 달려고 합니다.
- `Noncompliant`는 `규칙을 어긴 코드`
- `compliant`는 `규칙을 준수한`으로 번역했습니다.
- 원문 링크를 가급적 넣어서 혹시 번역이 힘든 부분이 있다면, 외부의 기여를 받을 수 있도록 하려합니다.

2022-12-30 06:16 UTC, isangu requested changes
우선 제목에 특수문자로 인해 정상적인 title 이 출력되지 않는 경우는 수정이 필요할 듯 합니다.

그리고, java 문서들은 기본적으로 java 태그들을 다 포함하는게 좋을 것 같은데 어떻게 생각하시나요.
미래에 rust(?) 문서를 번역하실수도 있으니...ㅋ...

readthis, 원문링크 등 md 파일에 필수적으로 들어갈만한 내용은 `CONTRIBUTING.md` 에 추가해놓을게요.

혹시 로컬에서 md 파일 작성 중에 만든 문서가 잘 만들어졌는지 보고싶다면, README 처럼 빌드하고 로컬에서 띄워볼 수 있어요!

리뷰하다보니 느끼는 건데, 한번에 PR 할 수 있는 문서의 양을 제한하는게 어떨까요?
한번에 10개 이상의 문서를 보려고 하다보니 뭔가 많은 양의 정보가 머리로 들어가서 잘 안담기는 느낌이...
한 5개 정도로 제한하는건 어떨까 싶은데 어떻게 생각하십니까 🙋

2022-12-30 06:16 UTC, isangu commented on _posts/2022-12-29-RSPEC-2203.md
> +title: "list::add"대신 "Streams"과 "collect"을 사용해야 합니다
quote, at 등의 특수 문자를 쓰는 경우 title 전체를 quote 로 묶어야 정상적으로 파싱이 되는 것 같아요.
제목이 제대로 파싱되지 않으면 아래처럼 타이틀이 노출되지 않습니다..ㅠ
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/24788424/210039200-fe732b3d-a05f-4478-a0b3-545d44ac9125.png">
single quote 로 감싸서 아래처럼 수정 부탁드리겠습니다. 🙇 동일한 내용은 `quote` 로 코멘트를 남겨놓을게요. 
`'"list::add"대신 "Streams"과 "collect"을 사용해야 합니다'`

2022-12-30 06:16 UTC, isangu commented on _posts/2022-12-29-RSPEC-2203.md
> +  - readthis
tags 는 [] 형태로도 사용 가능하긴 해서, 참고차 코멘트 달아둡니다.
`tags: [CodeSmell, Minor, java:S2203, java8, readthis]`
중요한 내용은 readthis 를 붙이는 컨벤션은 좋은 것 같습니다. 👍👍

2022-12-30 06:16 UTC, isangu commented on _posts/2022-12-30-RSPEC-2143.md
> +title: "java.time"은 날짜와 시간을 표기하는데에만 사용되어야 합니다
`quote`

2022-12-30 06:16 UTC, isangu commented on _posts/2022-12-30-RSPEC-2789.md
> +title: "null"은 "Optional"에서 사용되선 안됩니다.
`quote`

2022-12-30 06:16 UTC, isangu commented on _posts/2022-12-30-RSPEC-3824.md
> +title: "Map.get"이나 value 테스트는 단일 메서드 호출을 사용하여야 합니다.
`quote`

2022-12-30 06:16 UTC, isangu commented on _posts/2022-12-30-RSPEC-3864.md
> +title: "Stream.peek" 사용은 조심해야 합니다
`quote`

2022-12-30 06:16 UTC, isangu commented on _posts/2022-12-30-RSPEC-4065.md
> +title: "ThreadLocal.withInitial"을 우선해서 사용하는게 좋습니다.
`quote`

2022-12-30 06:16 UTC, isangu commented on _posts/2022-12-30-RSPEC-3958.md
> +### 역자 참고
역자 참고도 좋네요 👍👍

2022-12-30 06:16 UTC, isangu commented on _posts/2022-12-30-RSPEC-3864.md
> +title: "Stream.peek" 사용은 조심해야 합니다
저희도 `.peek()` 쓰는곳이 일부 있던데... ㅋㅎ..

2022-12-30 09:02 UTC, isangu approved these changes

2022-12-30 09:02 UTC, merged

2023-01-01 12:24 UTC, GimunLee commented
@isangu @kok202 
리뷰가 늦어 죄송합니다. 옐의 의견주신 것처럼 5개로 제한하면 좋을 것 같아요.
수고 많으셨습니다.

2023-01-01 12:48 UTC, GimunLee commented on _posts/2022-12-30-RSPEC-3436.md
> +### <역>
@kok202 '<역>' 의도하신게 맞나요?

2023-01-01 12:50 UTC, GimunLee commented on _posts/2022-12-30-RSPEC-3824.md
> +왜냐하면 `computeIfAbsent`의 반환 값이 null 일 때는, 실제로 엔트리에 값을 넣지 않기 때문입니다. (^역: 아래 코드 참조)
'^역' 의도하신걸까요?