RSPEC-1118, RSPEC-110
kantabile/sonarkube pull request #35
Opened 2023-01-16 16:05 UTC by kok202

2023-01-17 13:37 UTC, isangu requested changes
자바 태그랑, 중간에 번역이 조금 안된 부분이 보여서 코멘트 남겨놓았습니다!
확인 후에 수정 부탁드려요! 고생하셨습니다 👏👏

2023-01-17 13:37 UTC, isangu commented on _posts/java/2023-01-16-RSPEC-110.md
> +  - Code Smell
java 태그도 붙여주시면 감사하겠습니다 🙇‍♂️

2023-01-17 13:37 UTC, isangu commented on _posts/java/2023-01-16-RSPEC-110.md
> +- \*\* matches zero or more packages
요기 번역이 잘못되었거나, 안된 것 같아요! 확인 한번 부탁드리겠습니다 🙇‍♂️

2023-01-17 13:37 UTC, isangu commented on _posts/java/2023-01-16-RSPEC-1118.md
> +  - Major
요기도 java 태그 부탁드립니다!

2023-01-17 13:37 UTC, isangu commented on _posts/java/2023-01-16-RSPEC-110.md
> +이 규칙은 객체에서 시작하는 상속 트리의 깊이가 허용되는 값보다 커질 때 경종을 울립니다.
허용되는 값은 얼마일까요?... 이전 문서들에선 default threshold 가 있었던 것 같은데 이곳은 없네욧 🤔

2023-01-17 13:37 UTC, isangu commented on _posts/java/2023-01-16-RSPEC-1118.md
> +    throw new IllegalStateException("Utility class");
많이 보던 룰인데 보통은 lombok `@RequiredArgsConstructor(access = AccessLevel.PRIVATE)` 정도로 처리하는데,
Exception throw 하는것도 괜찮네요 ㅎㅎ..

2023-01-17 15:00 UTC, kok202 commented on _posts/java/2023-01-16-RSPEC-110.md
> +이 규칙은 객체에서 시작하는 상속 트리의 깊이가 허용되는 값보다 커질 때 경종을 울립니다.
맨정신으로 다시보니, 이 문서 자체가 조금 이해가 안가는 부분이 있네요. 일단 의역해두고, 주의 문구 남겨두겠습니다.

2023-01-18 10:32 UTC, isangu approved these changes

2023-01-19 01:48 UTC, GimunLee approved these changes

2023-01-19 02:48 UTC, merged