docs: RSPEC-2157, RSPEC-3242, RSPEC-4042
kantabile/sonarkube pull request #40
Opened 2023-01-19 13:28 UTC by kok202

몇개 안되네요~ 설연휴 전에 마지막일 것 같은데, 다들 설 잘쇠시길 빕니다~~

2023-01-21 02:56 UTC, isangu requested changes
불필요한 본문과 통일성을 위해 일부 문구만 수정되면 좋겠습니다!
오늘도 고생하셨고, 브랜든도 즐거운 설 연휴되세요!! 🙇‍♂️🙇‍♂️

2023-01-21 02:56 UTC, isangu commented on _posts/java/2023-01-19-RSPEC-2157.md
> +Removing the Cloneable implementation and providing a good copy constructor is another viable (some say preferable) way of allowing a class to be copied.
영문 원본이 지워지질 않았군요!

2023-01-21 02:56 UTC, isangu commented on _posts/java/2023-01-19-RSPEC-2157.md
> +// 역자 참조: "기본으로 제공되는 clone은 shallow copy니까 deep copy로 오버라이딩해라"라는 의미로 보입니다.
이전에는 h3(###) 형식으로 쓰셨던 것 같은데, 통일성을 위해 수정되면 좋겠습니다!(코드 블럭으로 통일하는것도 괜찮을지도..??)

2023-01-24 05:47 UTC, ssungwxx approved these changes

2023-01-24 05:47 UTC, ssungwxx commented on _posts/java/2023-01-19-RSPEC-3242.md
> +더불어 메소드 호출이 아닌 다른 컨텍스트에서 사용되거나 loop에 대해 enhance된 파라미터도 예외 처리됩니다.
loop 에 대해 enhance된 파라미터가 잘 읽히지 않네요.
마땅한 문장이 없을지 고민되는데 떠오르지가 않네요

2023-01-26 07:43 UTC, kok202 commented on _posts/java/2023-01-19-RSPEC-2157.md
> +Removing the Cloneable implementation and providing a good copy constructor is another viable (some say preferable) way of allowing a class to be copied.
큽.. 민망하군요 ㅎㅎ;;

2023-01-26 07:47 UTC, kok202 commented on _posts/java/2023-01-19-RSPEC-2157.md
> +// 역자 참조: "기본으로 제공되는 clone은 shallow copy니까 deep copy로 오버라이딩해라"라는 의미로 보입니다.
사실 첨엔 중간에 잠깐 각주 같은걸로 넣고 싶었는데, 마크다운이 각주를 지원하지 않아서, 주석느낌으로 했습니다.
문맥 중간에 나왔으면 하는 내용인데, h3를 사용하면 문맥을 절단하는 느낌이라 애매하네요.
음... 컨벤션이 좀 애매한데, 코드 블락보다는 아래와 같이 표현하겠습니다!
```
> 역자 참조: "기본으로 제공되는 clone은 shallow copy니까 deep copy로 오버라이딩해라"라는 의미로 보입니다.
```

2023-01-26 07:49 UTC, kok202 commented on _posts/java/2023-01-19-RSPEC-3242.md
> +더불어 메소드 호출이 아닌 다른 컨텍스트에서 사용되거나 loop에 대해 enhance된 파라미터도 예외 처리됩니다.
넹,,, 저도 의역이라도 하고 싶은데 원문 번역 자체가 살짝 이해가 안되서 😭 일단은 주석으로 도움이 필요하다고 남겨뒀으니 해당 건은 마무리하겠습니다.

2023-01-27 05:07 UTC, isangu approved these changes

2023-01-27 05:08 UTC, merged