docs: RSPEC-1141, RSPEC-2675, RSPEC-3042, RSPEC-3358
kantabile/sonarkube pull request #51
Opened 2023-01-31 15:56 UTC by kok202

조금 쉬다가 다시왔습니다 ~ 점심 시간에 번역을 시도한다는 것은 빡센 생각이었군요. confusing 태그는 어렵지않아서 좋네요 👍

2023-02-02 09:36 UTC, GimunLee reviewed
수고하셨습니다. 👍 원문이랑 링크만 챙겨주시면 될 것 같네요!

2023-02-02 09:36 UTC, GimunLee commented on _posts/java/2023-02-01-RSPEC-2675.md
> +A readObject method is written when a Serializable object needs special handling to be rehydrated from file. It should be the case that the object being created by readObject is only visible to the t
원문이 삭제되지 않았네요~

2023-02-02 09:36 UTC, GimunLee commented on _posts/java/2023-02-01-RSPEC-3042.md
> +머리를 긁적이며 당신을 욕하겠죠.
ㅋㅋㅋㅋㅋㅋㅋ 미국식 표현

2023-02-02 09:36 UTC, GimunLee commented on _posts/java/2023-02-01-RSPEC-3358.md
> +> [원문으로 바로가기](https://rules.sonarsource.com/java/tag/confusing/RSPEC-5973)
https://rules.sonarsource.com/java/tag/confusing/RSPEC-3042
가 돼야할 것 같아요~

2023-02-02 09:36 UTC, GimunLee commented on _posts/java/2023-02-01-RSPEC-3358.md
> +그런 의미에서 `writeObject`를 `synchronized`로 선언해야할 상황이 없습니다. 그런데 클래스내에서 동기화와 관련된 메서드 중, `synchronized` 선언된 유일한 코드가 `writeObject`라면 매우 미심쩍습니다.
이런식이면 더 자연스럽지 않을까 의견 남겨요~ 물론 스킵하셔도 좋습니다. 👍

Nit: 
`writeObject`를 `synchronized`로 선언하는 것은 실제로 문제가 없지만 클래스 내에서 ~~~ 은 매우 미심쩍습니다.

2023-02-02 09:36 UTC, GimunLee commented on _posts/java/2023-02-01-RSPEC-3042.md
> +> [원문으로 바로가기](https://rules.sonarsource.com/java/tag/confusing/RSPEC-3042)
원문 링크 확인 부탁드려요~

2023-02-02 09:37 UTC, GimunLee approved these changes

2023-02-02 11:52 UTC, ssungwxx requested changes
리키가 말씀해주신 부분만 체크해주시면 될 것 같아요.
점심시간에는 앉아있기보다는 산책 어떠신가요!

2023-02-02 12:32 UTC, isangu approved these changes
리키가 꼼꼼하게 리뷰해주신 덕분에 저는 딱히 코멘트 남길 것은 없네요!!
고생 많으셨습니다~~ 🙇‍♂️🙇‍♂️

2023-02-02 12:32 UTC, isangu commented on _posts/java/2023-02-01-RSPEC-2675.md
> +`Serializable` 객체가 파일에서 `rehydrate`를 할 때`readObject` 메서드는 특별히 다뤄줘야합니다.
혹시 이 `rehydrate` 라는 표현은 무슨 의미일까요?... 저만 모르는걸까요 😭😭😭
객체에서 [hydrate](https://stackoverflow.com/questions/6991135/what-does-it-mean-to-hydrate-an-object) 는 실제 데이터를 채우는 과정이라는 것 같은데, 유사한 의미로 해석하면 되겠..죠?

2023-02-02 12:32 UTC, isangu commented on _posts/java/2023-02-01-RSPEC-3042.md
> +무언가를 할 수 있다는 의미가 그렇게 해야한다는 의미는 아닙니다.
ㅋㅋㅋㅋ 좋은말이네요

2023-02-03 16:06 UTC, kok202 commented on _posts/java/2023-02-01-RSPEC-3358.md
> +> [원문으로 바로가기](https://rules.sonarsource.com/java/tag/confusing/RSPEC-5973)
리뷰 디테일이...ㄷㄷ;; 챙겨주셔서 감사합니다

2023-02-03 16:26 UTC, kok202 commented on _posts/java/2023-02-01-RSPEC-2675.md
> +`Serializable` 객체가 파일에서 `rehydrate`를 할 때`readObject` 메서드는 특별히 다뤄줘야합니다.
엇 그러게요... hydrate이라는 개념은 저는 nextjs + mobx를 다루면서 몇 번 접해보긴 했는데요. 
제가 당시에 이해한 hydrate은 SSR하면서 사용했던 mobx state를 client 쪽으로 내려줘서 client가 mobx state를 [복원하는 과정](https://dev.to/ivandotv/mobx-server-side-rendering-with-next-js-4m18)이었습니다. 그래서 말씀하신대로 객체에 데이터를 넣어주는 개념으로 이해하고 있었고요. 근데 궁금해서 다시 찾아보니 또 약간 [다른 내용](https://helloinyong.tistory.com/315)도 많네요..?

그래서 저는 `rehydrate` 가 serialize -> deserialize 를 과정이라고 생각했습니다.
결과적으로 그렇지 않을까요...?

chatgpt 의 의견은 restore 라고 하시네요.
![image](https://user-images.githubusercontent.com/39543643/216655268-03fbc85e-936f-476e-9698-5f346bd4f488.png)

2023-02-09 13:10 UTC, merged