RSPEC-5979, RSPEC-6073, RSPEC-5977, RSPEC-3414, RSPEC-3658
kantabile/sonarkube pull request #64
Opened 2023-02-13 07:50 UTC by GimunLee

코로나에 걸려서 오랜만에 복귀 했습니다...

2023-02-14 15:43 UTC, kok202 approved these changes
고생하셨습니다~ 오늘 되게 알찬 내용이 많네요

2023-02-15 14:20 UTC, isangu requested changes
몇 가지 오타가 보여 Request Changes 드립니다!! 수정 부탁드릴게요 🙏
고생 많으셨습니다!

2023-02-15 14:20 UTC, isangu commented on _posts/java/2023-02-13-RSPEC-3414.md
> +테스트 클래스를 프로덕션이 아닌 별도의 패키지로 분리하여 테스트 클래스에 의해 오염되거나 부풀어 오르지 않도록 하는 것이 좋습니다.
[nit] 영어의 세계는 오묘하네요.. 프로덕션 패키지에 테스트 코드가 넘쳐나선 안된다 같은 느낌으로 번역되는게 저는 좀 더 와닿는데, 부풀어 오르다 라고 하니 뭔가 어색하달까요?.... 리키는 어떻게 생각하시나요? 😅

2023-02-15 14:20 UTC, isangu commented on _posts/java/2023-02-13-RSPEC-3658.md
> +유닛 테스트 코드가 예외를 던질 때, 테스트는 스스로 실패합니다. 그러므로 실패를 탐지하기 위해 try-cath 문으로 테스트 코드를 감쌀 필요가 없습니다. 대신에 함수 시그니처에 예외 타입을 옮겨 간소화 할 수 있습니다.
오타가 있네요! try-cath -> try-catch

2023-02-15 14:20 UTC, isangu commented on _posts/java/2023-02-13-RSPEC-3658.md
> +이 규칙은 실패 assertion이 cath 블럭에 있는 경우 문제를 제기합니다.
마찬가지로 cath -> catch!

2023-02-15 14:20 UTC, isangu commented on _posts/java/2023-02-13-RSPEC-5977.md
> +테스트트는 항상 다음을 만족해야만 합니다:
오타가 있습니다! 테스트트는 -> 테스트는

2023-02-15 14:20 UTC, isangu commented on _posts/java/2023-02-13-RSPEC-5977.md
> +랜덤 값을 확실하게 기록하여 실패를 재현할 수 있어야 합니다. 몇가지 라이브러리가 이것들을 쉽게 만들어줍니다. jqwik와 같은 property-based 테스트 라이브러리를 예시로 사용할 수 있습니다.
오호.. [jqwik](https://jqwik.net/) 는 처음들어봤는데, 하나 배워갑니다! PBT(property-based-test) 라는 개념도요!

2023-02-15 14:20 UTC, isangu commented on _posts/java/2023-02-13-RSPEC-5979.md
> +@Mock, @Spy, @Captor, @InjectMocks와 같은 Mockito 어노티에션이 달린 객체는 명확하게 초기화될 필요가 있습니다.
오타가 있습니다! 어노티에션 -> 어노테이션

2023-02-16 11:56 UTC, GimunLee commented on _posts/java/2023-02-13-RSPEC-3414.md
> +테스트 클래스를 프로덕션이 아닌 별도의 패키지로 분리하여 테스트 클래스에 의해 오염되거나 부풀어 오르지 않도록 하는 것이 좋습니다.
다시 보니 너무 어색하네요 ㅋㅋㅋ 수정했습니다. 👍

2023-02-16 11:58 UTC, GimunLee commented
다시 보니 오타가 왜 이렇게 많나요..? 감사합니다 옐!

2023-02-18 05:36 UTC, isangu approved these changes

2023-02-18 05:36 UTC, merged