docs: RSPEC-2308, RSPEC-2864, RSPEC-3631
kantabile/sonarkube pull request #7
Opened 2023-01-01 17:55 UTC by kok202

## 참고
performance tag 번역중인데, 이게 생각해보니 태그가 여러개 달릴수 있는 규칙들이 있어서, 이미 번역된 문서가 있을 수 있네요.
번역전에 태그 잘 확인하고 이미 번역이 완료된 태그가 있는지 확인하심이 좋아보입니다.
![image](https://user-images.githubusercontent.com/39543643/210180283-1be3388e-cda8-42e5-b1f5-44aaf6177768.png)

## 브랜치 이름에 대하여
여러번 작업하다 보면 브랜치 이름이 매우 애매해질것 같은데요.
그냥 간단하게 `trans/{tagname}-{yyyy-mm-dd}`로 가는게 어떨까 제의드립니다. e.g) `trans/performance-2023-01-02`

2023-01-02 00:35 UTC, GimunLee commented
@kok202 
저는 좋습니다~

2023-01-04 07:47 UTC, isangu requested changes
오타 및 주석만 수정해주세요!!~ 고생하셨습니다 👍👍

2023-01-04 07:47 UTC, isangu commented on _posts/2023-01-02-RSPEC-2308.md
> +file.deleteOnExit();  // Noncompliant
통일성을 위해 주석에 noncompliant 도 `규칙을 어긴 코드` 로 바꾸는것이 좋겠습니다

2023-01-04 07:47 UTC, isangu commented on _posts/2023-01-02-RSPEC-3631.md
> +하지만, Primmitives(기본 자료형) 배열에 사용되는 경우 `Arrays.asList`을 사용하게 되면, boxed types(객채형)의 리스트 생성자를 강제하게 되고 이를 stream에 사용합니다.
오타가 있습니다. `Primmitives` -> `Primitives`, `boxed types(객채형)` -> `boxed types(객체형)`

2023-01-04 12:39 UTC, GimunLee commented on _posts/2023-01-02-RSPEC-3631.md
> +하지만, Primmitives(기본 자료형) 배열에 사용되는 경우 `Arrays.asList`을 사용하게 되면, boxed types(객채형)의 리스트 생성자를 강제하게 되고 이를 stream에 사용합니다.
와우 예리하네시네요

2023-01-04 13:02 UTC, GimunLee reviewed
옐이 말씀하신 부분만 수정되면 될 것 같네요 👍

2023-01-04 13:29 UTC, kok202 commented
반영하였습니다👍

2023-01-04 13:35 UTC, GimunLee approved these changes

2023-01-04 13:35 UTC, GimunLee commented on _posts/2023-01-02-RSPEC-3631.md
> -하지만, Primmitives(기본 자료형) 배열에 사용되는 경우 `Arrays.asList`을 사용하게 되면, boxed types(객채형)의 리스트 생성자를 강제하게 되고 이를 stream에 사용합니다.
객채형.. 은 차마 못 봤네요 ㅋㅋㅋ 👍

2023-01-05 00:56 UTC, isangu approved these changes

2023-01-05 00:56 UTC, merged