docs: RSPEC-2165, RSPEC-2232, RSPEC-2629, RSPEC-4929, RSPEC-5361
kantabile/sonarkube pull request #8
Opened 2023-01-02 15:50 UTC by kok202

2023-01-04 08:17 UTC, isangu requested changes
제목에 오타가 있어 Request Changes 드립니다! 좋은 내용이 많이 들어있네요 👍👍

2023-01-04 08:17 UTC, isangu commented on _posts/2023-01-03-RSPEC-2165.md
> +title: '"finalize"에서는 필드 값을 null로 변경해선 안됩니다.'
finalize 는 [jdk 18 부터는 deprecated](https://www.itworld.co.kr/howto/224419) 될 예정인가보네요..
몰랐던 내용인데 흥미로웠습니다👍

2023-01-04 08:17 UTC, isangu commented on _posts/2023-01-03-RSPEC-5361.md
> +title: 'Primitive 배열에는 "Arrays.stream"이 사용되어야 합니다'
제목이 잘못된것 같습니다. `"String#replaceAll" 보다는 "String#replace" 를 사용해야 합니다.` 정도이려나요?

2023-01-04 08:17 UTC, isangu commented on _posts/2023-01-03-RSPEC-5361.md
> +- {rule:java:S4248} - Regex patterns should not be created needlessly
https://rules.sonarsource.com/java/RSPEC-4248 링크를 함께 다는건 어떨까요?
나중에 번역하고 저희 페이지 링크로 걸어두실 생각이었다면 TODO 정도는 넣어줘야 잊지 않을 것 같습니다

2023-01-04 13:32 UTC, kok202 commented on _posts/2023-01-03-RSPEC-5361.md
> +title: 'Primitive 배열에는 "Arrays.stream"이 사용되어야 합니다'
복붙의 폐해.... 민망하군요...😂

2023-01-04 13:35 UTC, kok202 commented
반영완료하였습니다👍

2023-01-04 13:35 UTC, GimunLee approved these changes
수고하셨습니다.

2023-01-05 00:57 UTC, isangu approved these changes

2023-01-05 00:57 UTC, merged